"""
ImageSet Generator - OpenShift ImageSetConfiguration Generator

A tool for generating oc-mirror ImageSetConfiguration YAML files
for disconnected OpenShift installations.
"""

from .generator import ImageSetGenerator
from .constants import (
    TLS_VERIFY,
    TIMEOUT_OPM_RENDER,
    TIMEOUT_OC_MIRROR_SHORT,
    TIMEOUT_OC_MIRROR_MEDIUM,
    TIMEOUT_OC_MIRROR_LONG,
    TIMEOUT_CATALOG_DISCOVERY,
    DEFAULT_PORT,
    DEBUG_MODE,
    PROJECT_ROOT,
    VERSION_PATTERN,
    CHANNEL_PATTERN,
    BASE_CATALOGS,
    OPERATOR_MAPPINGS,
    DATA_DIR,
    FRONTEND_BUILD_DIR,
    CACHE_OCP_VERSIONS,
    CACHE_OCP_CHANNELS,
    CACHE_CHANNEL_RELEASES,
    API_VERSION,
    API_NAME,
)
from .validation import (
    validate_version,
    validate_channel,
    validate_catalog_url,
    safe_path_component,
    ValidationError,
)
from .exceptions import (
    ImageSetGeneratorError,
    CatalogError,
    CatalogRenderError,
    CatalogParseError,
    OperatorError,
    OperatorNotFoundError,
    InvalidChannelError,
    VersionError,
    InvalidVersionError,
    VersionComparisonError,
    ConfigurationError,
    FileOperationError,
    NetworkError,
    GenerationError,
)

__version__ = "1.0.0"
__all__ = [
    "ImageSetGenerator",
    "TLS_VERIFY",
    "TIMEOUT_OPM_RENDER",
    "TIMEOUT_OC_MIRROR_SHORT",
    "TIMEOUT_OC_MIRROR_MEDIUM",
    "TIMEOUT_OC_MIRROR_LONG",
    "TIMEOUT_CATALOG_DISCOVERY",
    "DEFAULT_PORT",
    "DEBUG_MODE",
    "PROJECT_ROOT",
    "VERSION_PATTERN",
    "CHANNEL_PATTERN",
    "BASE_CATALOGS",
    "OPERATOR_MAPPINGS",
    "DATA_DIR",
    "FRONTEND_BUILD_DIR",
    "CACHE_OCP_VERSIONS",
    "CACHE_OCP_CHANNELS",
    "CACHE_CHANNEL_RELEASES",
    "API_VERSION",
    "API_NAME",
    "validate_version",
    "validate_channel",
    "validate_catalog_url",
    "safe_path_component",
    "ValidationError",
    "ImageSetGeneratorError",
    "CatalogError",
    "CatalogRenderError",
    "CatalogParseError",
    "OperatorError",
    "OperatorNotFoundError",
    "InvalidChannelError",
    "VersionError",
    "InvalidVersionError",
    "VersionComparisonError",
    "ConfigurationError",
    "FileOperationError",
    "NetworkError",
    "GenerationError",
]
