name: Container Image (GHCR)

on:
  push:
    branches: [ main ]
    tags:
      - "v*"
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and publish container image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/imageset-generator
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short,prefix=sha-,enable={{is_default_branch}}
            type=ref,event=tag
            type=raw,value=latest,enable={{is_tag}}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.title=imageset-generator
            org.opencontainers.image.description=Builds the imageset-generator app container

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Containerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
